name: Python package

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [macos-latest, ubuntu-latest, windows-latest]
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install opencv-python numpy
      - name: Test 
        env:
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        run: |
          cd tweetcapture/tests
          python -m unittest
      - name: Screenshot to Artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: results-${{ matrix.os }}
          path: |
            tweetcapture/tests/*.png
            tweetcapture/tests/*.jpg
          if-no-files-found: ignore
